# Práctica de la librería Numpy

En este notebook, se desarrollarán una serie de tareas utilizando la librería Numpy (Numerical Python).

Se proponen y documentan posibles formas de resolver los ejercicios, pero las mismas no son únicas.

Siempre es una buena idea verificar la [Documentación Oficial de Numpy](https://numpy.org/devdocs/user/index.html), donde es posible encontrar todo tipo de información referida a esta librería. Y si te quedas trabado, busca en Google "como hacer [algo] con Numpy". Hay enormes probabilidades de que esa pregunta ya haya sido respondida!

In [ ]:
# Importamos Numpy con su abreviación "np"
import numpy as np



In [ ]:
# Podemos crear arrays de una dimensión con la función np.array()
array_unidimensional = np.array([1, 2, 3, 4, 5])

# O un array de dos dimensiones (bidimensional)
array_bidimensional = np.array([[1, 2, 3],
                                [4, 5, 6]])

# O un array de tres dimensiones (tridimensional)
array_tridimensional = np.array([[[1, 2, 3],
                                  [4, 5, 6]],
                                 [[7, 8, 9],
                                  [10, 11, 12]]])


Para cada uno de estos arrays, podemos obtener sus propiedades, tales como su "forma", número de dimensiones, tipos de datos y tamaño.

In [ ]:
# Atributos del array unidimensional (forma, número de dimensiones, tipos de datos, tamaño, y tipo)
array_unidimensional.shape, array_unidimensional.ndim, array_unidimensional.dtype, array_unidimensional.size, type(array_unidimensional)


((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [ ]:
# Atributos del array bidimensional
array_bidimensional.shape, array_bidimensional.ndim, array_bidimensional.dtype, array_bidimensional.size, type(array_bidimensional)


((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [ ]:
# Atributos del array tridimensional
array_tridimensional.shape, array_tridimensional.ndim, array_tridimensional.dtype, array_tridimensional.size, type(array_tridimensional)


((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [ ]:
# Importamos pandas como pd, y creamos un DataFrame a partir del array bidimensional
import pandas as pd


datos = pd.DataFrame(array_bidimensional)
datos


0  1  2
0  1  2  3
1  4  5  6

In [ ]:
# Creamos un array de tamaño 4x3, formado únicamente por unos (1)
unos = np.ones((4, 3))
unos


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Creamos un array de tamaño 2x4x3, formado únicamente por ceros (0)
ceros = np.zeros((2, 4, 3))
ceros


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# Creamos un array de números en el rango de 0 a 100, con un paso de 5
array_1 = np.arange(0, 101, 5)
array_1


array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [ ]:
# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (2, 5)
array_2 = np.random.randint(0, 10, (2, 5))
array_2


array([[4, 0, 2, 9, 9],
       [1, 6, 7, 9, 6]])

In [ ]:
# Creamos un array de números aleatorios decimales comprendidos en entre 0 y 1, de tamaño (3, 5)
array_3 = np.random.random((3, 5))
array_3


array([[0.78960963, 0.53586831, 0.61536798, 0.49773738, 0.81630811],
       [0.78210423, 0.62288851, 0.64106118, 0.27236361, 0.32194746],
       [0.86352258, 0.29090749, 0.8641    , 0.84430808, 0.93128834]])

In [ ]:
# Establecemos la "semilla" de números aleatorios en 27
np.random.seed(27)

# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (3, 5)
array_4 = np.random.randint(0, 10, (3, 5))
array_4


array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2],
       [1, 1, 4, 6, 3]])

¿Qué ocurre al correr la última celda nuevamente, a diferencia de las anteriores?

In [ ]:
# Encontramos los valores únicos del array_4
np.unique(array_4)


array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [ ]:
# Extraemos el elemento de índice 1 del array_4
array_4[1]


array([5, 8, 9, 1, 2])

In [ ]:
# Extraemos las primeras dos filas del array_4
array_4[:2]


array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2]])

In [ ]:
# Extraemos los dos primeros datos de las primeras dos filas del array_4
array_4[:2, :2]


array([[3, 8],
       [5, 8]])

In [ ]:
# Creamos dos arrays de tamaño 3x4: uno relleno de números aleatorios entre 0 y 10, y otro relleno de unos
array_5 = np.random.randint(0, 10, (3, 4))
array_6 = np.ones((3, 4))


In [ ]:
# invocamos el array_5
array_5


array([[3, 0, 5, 3],
       [3, 6, 7, 2],
       [7, 8, 5, 7]])

In [ ]:
# invocamos el array_6
array_6


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Sumamos los dos arrays
array_5 + array_6


array([[4., 1., 6., 4.],
       [4., 7., 8., 3.],
       [8., 9., 6., 8.]])

In [ ]:
# Creamos ahora un array de tamaño (4,3) lleno de unos
array_7 = np.ones((4, 3))
array_7


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Intentaremos sumar los arrays 6 y 7
array_6 + array_7


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

¿A qué se debe el error anterior? ¿Qué deberíamos tener en cuenta para que no suceda?

In [ ]:
# Entonces crearemos otro array de tamaño (4,3) lleno de unos
array_8 = np.ones((4, 3))
array_8


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Restamos el array_8 al array_7
array_8 - array_7


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Creamos otros dos arrays de tamaño 3x3 con números aleatorios del 1 al 5
array_9 = np.random.randint(1, 5, (3, 3))
array_10 = np.random.randint(1, 5, (3, 3))


In [ ]:
# invocamos el array_9
array_9


array([[2, 3, 4],
       [1, 4, 4],
       [2, 3, 4]])

In [ ]:
# invocamos el array_10
array_10


array([[2, 1, 4],
       [4, 1, 2],
       [2, 4, 1]])

In [ ]:
# Multiplicamos los últimos dos arrays entre sí
array_9 * array_10


array([[ 4,  3, 16],
       [ 4,  4,  8],
       [ 4, 12,  4]])

In [ ]:
# Elevamos el array_9 al cuadrado
pow(array_9, 2)


array([[ 4,  9, 16],
       [ 1, 16, 16],
       [ 4,  9, 16]])

In [ ]:
# Buscamos la raíz cuadrada del array_10
np.sqrt(array_10)


array([[1.41421356, 1.        , 2.        ],
       [2.        , 1.        , 1.41421356],
       [1.41421356, 2.        , 1.        ]])

In [ ]:
# Hallamos el promedio de los valores del array_9
array_9.mean()


3.0

In [ ]:
# Hallamos el valor máximo de los valores del array_9
array_9.max()


4

In [ ]:
# Hallamos el valor mínimo de los valores del array_9
array_9.min()


1

In [ ]:
# Cambiamos la forma del array_9 por una de 9x1, y lo almacenamos como array_11
array_11 = array_9.reshape((9, 1))


In [ ]:
# invocamos el array_11
array_11


array([[2],
       [3],
       [4],
       [1],
       [4],
       [4],
       [2],
       [3],
       [4]])

In [ ]:
# Transponemos el array_11
array_11.T


array([[2, 3, 4, 1, 4, 4, 2, 3, 4]])

In [ ]:
# Comparamos el array_9 y el array_10, para saber cuáles elementos del array_9 son mayores a los del array_10
array_12 = array_9 > array_10
array_12


array([[False,  True, False],
       [False,  True,  True],
       [False, False,  True]])

¿Qué tipos de datos forman parte del array de resultados?

In [ ]:
# Veamos sus nuevos tipos de datos
array_12.dtype


dtype('bool')

In [ ]:
# Alguno de los elementos del array_9 es igual su equivalente del array_10?
array_9 == array_10


array([[ True, False,  True],
       [False, False, False],
       [ True, False, False]])

In [ ]:
# Comparamos nuevamente ambos arrays, en esta ocasión con >=
array_9 >= array_10


array([[ True,  True,  True],
       [False,  True,  True],
       [ True, False,  True]])

In [ ]:
# Buscamos los elementos del array_9 que son mayores a 2
array_9 > 2


array([[False,  True,  True],
       [False,  True,  True],
       [False,  True,  True]])

In [ ]:
# Ordenamos de menor a mayor los elementos dentro del array_9
np.sort(array_9)


array([[2, 3, 4],
       [1, 4, 4],
       [2, 3, 4]])